# Generated by Django 3.1 on 2022-05-02 13:27

from django.db import migrations, models
import djongo.models.fields
import shopapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField()),
                ('brand', djongo.models.fields.EmbeddedField(model_container=shopapp.models.Brand, model_form_class=shopapp.models.BrandForm)),
                ('created_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
