# Generated by Django 3.1 on 2022-05-02 14:10

from django.db import migrations, models
import djongo.models.fields
import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sku', models.IntegerField()),
                ('brand', djongo.models.fields.EmbeddedField(model_container=shopapp.models.Brand, model_form_class=shopapp.models.BrandForm)),
                ('created_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
